import type { TGameRecordCollection } from '@/widgets/game-record-collection/model';
import { Platform } from '@/entities/game-record/model';

const gameRecordCollection: TGameRecordCollection = {
  2024: [
    {
      id: 1,
      title: 'Batman: Arkham City',
      platform: Platform.windows,
      releaseYear: 2011,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/batman-arkham-city.png)',
      isDlc: false,
    },
    {
      id: 2,
      title: 'Spyro 3: Year of the Dragon',
      platform: Platform.ps4,
      releaseYear: 2018,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/spyro-year-of-the-dragon.png)',
      isDlc: false,
    },
    {
      id: 3,
      title: 'Spyro 2: Ripto\'s Rage',
      platform: Platform.ps4,
      releaseYear: 2018,
      finished: true,
      mastered: true,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/spyro-2-riptos-rage.jpg)',
      isDlc: false,
    },
    {
      id: 4,
      title: 'Spyro The Dragon',
      platform: Platform.ps4,
      releaseYear: 2018,
      finished: true,
      mastered: true,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/spyro-the-dragon.jpg)',
      isDlc: false,
    },
    {
      id: 5,
      title: 'Doom 3: Resurrected of Evil',
      platform: Platform.ps4,
      releaseYear: 2019,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/doom3roe.png)',
      isDlc: true,
    },
    {
      id: 5,
      title: 'Doom 3',
      platform: Platform.ps4,
      releaseYear: 2019,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/doom3.jpg)',
      isDlc: false,
    },
    {
      id: 6,
      title: 'Far Cry 5',
      platform: Platform.ps4,
      releaseYear: 2018,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/far-cry-5.png)',
      isDlc: false,
    },
    {
      id: 7,
      title: 'Doom Eternal',
      platform: Platform.ps5,
      releaseYear: 2020,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/doom-eternal.png)',
      isDlc: false,
    },
    {
      id: 8,
      title: 'Resident Evil Village',
      platform: Platform.ps5,
      releaseYear: 2021,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/resident-evil-village.png)',
      isDlc: false,
    },
    {
      id: 9,
      title: 'Diablo IV',
      platform: Platform.ps5,
      releaseYear: 2023,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/diablo-4.png)',
      isDlc: false,
    },
    {
      id: 10,
      title: 'Dead Space 2',
      platform: Platform.windows,
      releaseYear: 2011,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/dead-space-2.png)',
      isDlc: false,
    },
    {
      id: 11,
      title: 'Resident Evil 4',
      platform: Platform.windows,
      releaseYear: 2023,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/resident-evil-4.png)',
      isDlc: false,
    },
    {
      id: 12,
      title: 'Diablo III',
      platform: Platform.ps3,
      releaseYear: 2012,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/diablo-3.png)',
      isDlc: false,
    },
    {
      id: 13,
      title: 'RAGE',
      platform: Platform.windows,
      releaseYear: 2010,
      finished: true,
      mastered: false,
      favourite: false,
      betterTogether: false,
      playingYear: 2024,
      imagePath: 'url(/src/entities/game-record/ui/images/rage.jpg)',
      isDlc: false,
    },
  ],
};

import { HttpResponse, http } from "msw";

const getWholeGameRecordCollectionResolver = http.get('/api/v1/game-record-collection', () => HttpResponse.json(gameRecordCollection));

export const gameRecordCollectionMockHandlers = [getWholeGameRecordCollectionResolver];

export const GameRecordCollectionService = {
  getAll: async () => {
    const res = await fetch('/api/v1/game-record-collection');
    const resBody = await res.json();
    return resBody;
  },
};